/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package terserah
fun isPrime(x: Int, i: Int = 2): String{
    if (x <= 3){
        return if (x != 1) "is prime number"
        else "is not a prime number"
    }
    if (x % i == 0) return "is not prime number"
    if (i * i > x) return "is prime number"
    return isPrime(x, i + 1)
}

fun main() {
    println(isPrime(3))
    println(isPrime(3))
    println(isPrime(4))
    println(isPrime(7))
}
